### ISSUE TITLE
Create JS tests for Tooltip.js 

### ISSUE THREAD

**Issue by misscs** [CasperSleep/nightshade-core#103]
### Vision

Write tests for Tooltip pattern using testing framework (#96). Achieve file code coverage > 90% (#102).
### Current State

No unit testing currently in `nightshade-core`.
### Scope
- [ ]

**Comment by stewartyu** [comment]
PR: https://github.com/CasperSleep/nightshade-core/pull/135

**Comment by stewartyu** [comment]
Merged
