### ISSUE TITLE
Create JS tests for Scrollto.js

### ISSUE THREAD

**Issue by misscs** [CasperSleep/nightshade-core#104]
### Vision

Write tests for [Scrollto.js](https://github.com/CasperSleep/nightshade-core/blob/v2.0.0-dev/src/animation/ScrollTo.js) pattern using testing framework (#96). Achieve file code coverage > 90% (#102).
### Current State

No unit testing currently in `nightshade-core`. 
### Affected Areas

This pattern is used by
- [Beacon](https://github.com/CasperSleep/nightshade-core/tree/v2.0.0-dev/src/beacon)
- [Scrollto_nav](https://github.com/CasperSleep/nightshade-core/tree/v2.0.0-dev/src/scrollto_nav)

**Comment by stewartyu** [comment]
Merged
