### ISSUE TITLE
[Minor] Convert CTA Banner 

### ISSUE THREAD

**Issue by misscs** [CasperSleep/nightshade-core#11]
Referencing the Rails helper, create nunjucks macro for CTA banner.

<img width="722" alt="screen shot 2016-02-09 at 01 52 33" src="https://cloud.githubusercontent.com/assets/51812/12909676/7e10d0fa-ced1-11e5-85ae-9b5804a17c8c.png">
### Requirements
- Macro will allow developer to pass in custom text for the header. 
- Macro will allow developer to pass in custom text for the link (button).
- Macro will allow developer to pass in a custom href value for the link
- Macro will allow developer to pass in a different param for button type. Default is primary. 
- Macro will allow developers to specify various media types, i.e. videos and stills
- Macro and its necessary styles and JS will live in `/modules/cta_banner`
### Considerations
- Current CTA helper loads a video and a still image. Is it possible to only load video and use video poster attribute to set the still? JS would target the video based on media query to determine if to play or to show the poster.

**Comment by misscs** [comment]
Documentation from Nightshade v1. Shows what params we'll need. 

```
 // Param             |  Description
  // ----------------  | -----------------
  // `header_copy`     | Content for the headline
  // `header-class`    | Typography classes for the headline
  // `button_copy`     | Text for the button
  // `button_class`    | Classes for buttons. Pass only modifier. Default class is `btn`
  // `url`             | Link for the button
  // `height`          | Default is `300px`
  // `background_color`| Link for the button
  // `background_image`| Full cover image
```

**Comment by josephco** [comment]
This has been addressed in https://github.com/CasperSleep/nightshade-core/pull/48
