### ISSUE TITLE
Setup JavaScript testing framework

### ISSUE THREAD

**Issue by stewartyu** [CasperSleep/nightshade-core#96]
### Vision

Implement unit testing framework for JavaScript widgets. 
### Current State

No unit testing currently in `nightshade-core`.
### Scope
- [x] Implement testing framework (ideally Ava, or Mocha)
### Anti-Vision

Integration/system testing not required at this time.

**Comment by misscs** [comment]
Not going to run it via Gulp because NYC is not available for gulp. The plan is to run tests via NPM script.  Need to decide if we want have npm kick off the gulp process
